# osparc-simcore stack (framework stack)
# NOTES :
# LOGSPOUT_MULTILINE is used to tell to Logspout, which is used by GrayLog, to handle multiline support of the logs of the concerned container. Please add with every new osparc-simcore service.
# See this issue to have more informations : https://github.com/ITISFoundation/osparc-ops/issues/40
version: "3.7"
services:
  # need to pass self-signed certificate in /usr/local/share/ca-certificates and call update-ca-certificates
  storage:
    secrets:
        - source: rootca.crt
          target: /usr/local/share/ca-certificates/osparc.crt
    environment:
      # minio sdk uses this env to use self-signed certs
      - SSL_CERT_FILE=/usr/local/share/ca-certificates/osparc.crt