version: "3.8"
services:
  traefik:
    deploy:
      labels:
      - traefik.http.routers.${SIMCORE_STACK_NAME}_simcore_http.rule=(${MACHINE_FQDNS_TRAEFIK}) && PathPrefix(`/`) && ClientIP(${MAINTENANCE_TEAM_IPS_FORMATTED})
      - traefik.http.routers.${SIMCORE_STACK_NAME}_simcore_http.priority=2
