version: "3.8"
services:
  traefik:
    deploy:
      labels:
      - traefik.http.routers.${SWARM_STACK_NAME}_simcore_http.rule=(${MACHINE_FQDNS}) && PathPrefix(`/`) && ClientIP(`172.16.8.39`, `172.16.8.64`, `10.43.103.179`, `172.16.8.68`, `172.16.8.72`, `10.43.103.168`, `172.16.8.26`, `172.16.9.150`, `172.16.9.89`, `10.43.200.15`, `172.16.9.146`)
      - traefik.http.routers.${SWARM_STACK_NAME}_simcore_http.priority=2
