version: '3.7'
services:
  adminer:
    deploy:
      labels:
        - traefik.http.routers.adminer.tls=true
        - traefik.http.routers.adminer.tls.certresolver=myresolver
        - traefik.http.routers.adminer.entrypoints=https
