{
 "title": "SPARC DRC Metrics",
 "description": "SPARC DRC Metrics",
 "time": { "from": "now-3M", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "deployment", "label": "Deployment", "query": "production, staging" },
   { "name": "Postgresql", "query": "postgres" }
  ]
 },
 "panels": [
  { "title": "Number of users", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Total number of registered users who have accounts on oSPARC",
   "type": "stat",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(created_at,$__interval),\n  sum(count(id)) OVER (ORDER BY $__timeGroup(created_at,$__interval)) AS \"id\"\nFROM users\nWHERE\n  role != 'GUEST'\nGROUP BY 1\nORDER BY 1"
    }
   ]
  },
  {
   "title": "Total number of anonymous users who are redirected to oSPARC from the SPARC Portal",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "rawSql": "SELECT\n  $__timeGroupAlias(created_at,$__interval),\n  sum(count(id)) OVER (ORDER BY $__timeGroup(created_at,$__interval)) AS \"id\"\nFROM users\nWHERE\n  $__timeFilter(created_at) AND\n  role = 'GUEST' AND\n  created_ip NOT LIKE '195.176.8.%'\nGROUP BY 1\nORDER BY 1"
    }
   ]
  },
  { "title": "Login rate", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 } },
  {
   "title": "Average number of logins per month to oSPARC averaged over the quarter reported on",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (endpoint)  (rate(http_requests_total{endpoint=~\"/v0/me\", http_status=~\"2[0-9]+\", app_name=~\".+webserver\", deployment=\"$deployment\"}[30d]))*60*60*24*30",
     "legendFormat": "endpoint: {{endpoint}}"
    }
   ]
  },
  { "title": "Service and model usage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 24 } },
  {
   "title": "Average number of times per month a service on the oSPARC platform was ran, up to the top 10 most popular services averaged over the quarter reported on",
   "type": "graph",
   "gridPos": { "h": 11, "w": 8, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "topk(10, rate({__name__=~\"simcore_simcore_service_(director|webserver)_services_started_total:sum_by_service_key_service_tag\", deployment=\"$deployment\"}[30d])*60*60*24*30)",
     "legendFormat": "{{service_key}}:{{service_tag}}"
    }
   ]
  },
  { "title": "Data/Hardware usage", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 36 } },
  {
   "title": "Overall data storage that has been consumed over the quarter reported on [GB]",
   "type": "graph",
   "gridPos": { "h": 11, "w": 8, "x": 0, "y": 37 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "sum(node_filesystem_size_bytes{mountpoint=\"/\"} - node_filesystem_avail_bytes{mountpoint=\"/\"})",
     "legendFormat": "data usage"
    }
   ]
  },
  {
   "title": "Total CPU consumption over the quarter reported on [cpu-hours]",
   "type": "graph",
   "gridPos": { "h": 10, "w": 8, "x": 0, "y": 48 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "node_cpu_seconds_total:nonidle_sum_over_nodes/3600",
     "legendFormat": "total cpu hours"
    },
    {
     "expr": "increase(node_cpu_seconds_total:nonidle_sum_over_nodes[1h])/3600",
     "legendFormat": "increase cpu hours"
    }
   ]
  }
 ]
}