version: "3.7"
services:
  jaeger:
    dns: 
      8.8.8.8
    image: jaegertracing/all-in-one:1.18.1
    command: >
      --query.base-path=/jaeger
      --memory.max-traces=200

    init: true
    networks:
      - public
      - monitored
    environment:
      COLLECTOR_ZIPKIN_HTTP_PORT: 9411
    deploy:
      labels:
        - traefik.enable=true
        - traefik.docker.network=${PUBLIC_NETWORK}
        - traefik.http.services.jaeger.loadbalancer.server.port=16686
        - traefik.http.routers.jaeger.rule=Host(`${MONITORING_DOMAIN}`) && PathPrefix(`/jaeger`)
        - traefik.http.routers.jaeger.entrypoints=https
        - traefik.http.routers.jaeger.tls=true
        - traefik.http.routers.jaeger.middlewares=ops_whitelist_ips@docker, ops_auth@docker, ops_gzip@docker
      resources:
        limits:
          memory: 2048M

networks:
  public:
    external: true
    name: ${PUBLIC_NETWORK}
  monitored:
    name: ${MONITORED_NETWORK}
    external: true
