version: '3.7'
services:
  graylog:
    dns: 
      8.8.8.8
    deploy:
      placement:
        constraints:
          - node.labels.ops==true
          - node.labels.graylog==true
  mongodb:
    deploy:
      placement:
        constraints:
          - node.labels.ops==true
          - node.labels.graylog==true
  elasticsearch:
    deploy:
      placement:
        constraints:
          - node.labels.ops==true
          - node.labels.graylog==true