version: "3.7"
services:
  mongodb:
    deploy:
      placement:
        constraints:
          - node.labels.graylog==true
          - node.labels.ops==true

  elasticsearch:
    deploy:
      placement:
        constraints:
          - node.labels.graylog==true
          - node.labels.ops==true
          
  graylog:
    deploy:
      placement:
        constraints:
          - node.labels.graylog==true
          - node.labels.ops==true