version: '3.7'
services:
  graylog:
    deploy:
      labels:
        - traefik.http.routers.graylog.tls=true
        - traefik.http.routers.graylog.entrypoints=https
        - traefik.http.routers.graylog.tls.certresolver=lehttpchallenge
