version: '3.7'
services:
  traefik:
    command:
      - '--api=true'
      - '--api.dashboard=true'
      - '--log.level=WARNING'
      #   - '--accesslog=true'
      - '--metrics.prometheus=true'
      - '--metrics.prometheus.addEntryPointsLabels=true'
      - '--metrics.prometheus.addServicesLabels=true'
      - '--entryPoints.metrics.address=:8082'
      - '--metrics.prometheus.entryPoint=metrics'
      - '--entryPoints.http.address=:80'
      - '--entryPoints.https.address=:443'
      - '--entryPoints.master_postgres.address=:5432'
      - '--entryPoints.smtp.address=:25'
      - '--providers.docker.endpoint=unix:///var/run/docker.sock'
      - '--providers.docker.swarmMode=true'
      - '--providers.docker.exposedByDefault=false'
      - '--tracing=true'
      - '--tracing.jaeger=true'
      - '--tracing.jaeger.samplingServerURL=http://jaeger:5778/sampling'
      - '--tracing.jaeger.localAgentHostPort=jaeger:6831'
      - "--providers.docker.constraints=!LabelRegex(`io.simcore.zone`, `.+`)"
      - "--entryPoints.https.forwardedHeaders.insecure"
      - "--certificatesresolvers.customcertresolver.acme.dnschallenge.provider=rfc2136"
      - "--certificatesresolvers.customcertresolver.acme.dnschallenge.delaybeforecheck=120"
      - "--certificatesresolvers.customcertresolver.acme.email=${OSPARC_DEVOPS_MAIL_ADRESS}"
      - "--certificatesresolvers.customcertresolver.acme.storage=/letsencrypt/acme.json"
      # For debug purpose, to avoid being ban by let's encrypt servers
      #  - "--certificatesresolvers.customcertresolver.acme.caserver=https://acme-staging-v02.api.letsencrypt.org/directory"
      - "--certificatesresolvers.customcertresolver.acme.dnschallenge.resolvers=${CERTIFICATE_RESOLVE_DNS_CHALLANGE_IP}"
    volumes:
      - "letsencrypt_certs:/letsencrypt"
    env_file:
      - .env
    deploy:
      placement:
        constraints:
          - node.labels.traefik==true
  whoami:
    deploy:
      labels:
        - traefik.http.routers.whoami.tls.certresolver=customcertresolver

volumes:
  letsencrypt_certs:
