version: '3.7'
services:
  portainer:
    deploy:
      labels:
        - traefik.http.routers.portainer.tls=true
        - traefik.http.routers.portainer.entrypoints=https
        - traefik.http.routers.portainer.tls.certresolver=lehttpchallenge
