{
 "title": "Minio V2",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "server",
    "label": "server",
    "query": "minio_cluster_nodes_online_total"
   },
   { "name": "bucket", "label": "bucket", "query": "minio_bucket_usage_total_bytes" }
  ]
 },
 "panels": [
  {
   "title": "Uptime for MinIO server",
   "type": "stat",
   "gridPos": { "h": 3, "w": 7, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "minio_node_process_uptime_seconds{server=~\"$server\"}\n"
    }
   ]
  },
  {
   "title": "Free space in the cluster",
   "type": "graph",
   "gridPos": { "h": 5, "w": 7, "x": 7, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum by (range) (\nminio_cluster_capacity_usable_free_bytes\n)\n"
    }
   ]
  },
  {
   "title": "Bucket size",
   "type": "graph",
   "gridPos": { "h": 5, "w": 7, "x": 14, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum by (range) (\nminio_bucket_usage_total_bytes{bucket=~\"$bucket\"}\n)"
    }
   ]
  },
  {
   "title": "Nodes online",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum by (range) (\nminio_cluster_nodes_online_total\n)"
    }
   ]
  },
  {
   "title": "Nodes offline",
   "type": "stat",
   "gridPos": { "h": 3, "w": 3, "x": 4, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum by (range) (\nminio_cluster_nodes_offline_total\n)"
    }
   ]
  },
  {
   "title": "Total number S3 requests with errors",
   "type": "graph",
   "gridPos": { "h": 5, "w": 7, "x": 7, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "(minio_s3_requests_errors_total{server=\"${server}\"})\n\n",
     "legendFormat": "Error: {{api}}"
    },
    {}
   ]
  },
  {
   "title": "Total number S3 requests",
   "type": "graph",
   "gridPos": { "h": 5, "w": 7, "x": 14, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "(\nminio_s3_requests_total{server=${server}}\n)\n"
    }
   ]
  },
  {
   "title": "Cluster total capacity",
   "type": "stat",
   "gridPos": { "h": 6, "w": 7, "x": 0, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum by (range) (\nminio_cluster_capacity_usable_total_bytes\n)\n"
    }
   ]
  },
  {
   "title": "Total number of objects per bucket",
   "type": "stat",
   "gridPos": { "h": 7, "w": 5, "x": 7, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum by (range) (\nminio_bucket_usage_object_total{bucket=~\"$bucket\"}\n)"
    }
   ]
  },
  {
   "title": "Object size distribution",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum by (range) (\r\n\tminio_bucket_objects_size_distribution{bucket=~\"$bucket\"}\r\n)\n",
     "legendFormat": "{{range}}"
    }
   ]
  },
  {
   "title": "Time elapsed since last self healing activity",
   "type": "stat",
   "gridPos": { "h": 3, "w": 7, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum by (range) (\nminio_heal_time_last_activity_nano_seconds{server=~\"$server\"}\n)"
    }
   ]
  },
  {
   "title": "Heal objects in error for the current healing session",
   "type": "stat",
   "gridPos": { "h": 3, "w": 7, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum by (range) (\nminio_heal_objects_error_total{server=~\"$server\"}\n)"
    }
   ]
  },
  {
   "title": "Objects healed in current self healing run",
   "type": "stat",
   "gridPos": { "h": 3, "w": 7, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum by (range) (\nminio_heal_objects_heal_total{server=~\"$server\"}\n)"
    }
   ]
  },
  {
   "title": "Objects scanned in current self healing run",
   "type": "stat",
   "gridPos": { "h": 3, "w": 7, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum by (range) (\nminio_heal_objects_total{server=~\"$server\"}\n)"
    }
   ]
  }
 ]
}