version: '3.7'
services:
  registry:
    environment:
      REGISTRY_HTTP_SECRET: "b494a25faa8d22e430e843e220e424e10ac84d2ce0e64231f5b636d21251eb6d267adb042ad5884cbff0f3891bcf911bdf8abb3ce719849ccda9a4889249e5c2"  
    deploy:
      labels:
        - traefik.http.routers.registry.tls=false
        - traefik.http.routers.registry.entrypoints=http
