# Minio config
scrape_configs:
  
    # to generate the token use the following
    # docker run -v /etc/ssl/certs:/etc/ssl/certs:ro --network host \
    #   -e MC_HOST_local="https://12345678:12345678@osparc.local:10000" \
    #   minio/mc admin prometheus generate local
 - job_name: minio-job
   bearer_token: ${MINIO_PROMETHEUS_TOKEN}
   metrics_path: /minio/prometheus/metrics
   scheme: https
   static_configs:
   - targets: ['storage.osparc.speag.com']
