# Minio config
scrape_configs:
  
    # to generate the token use the following
    # docker run -v /etc/ssl/certs:/etc/ssl/certs:ro --network host \
    #   -e MC_HOST_local="https://12345678:12345678@osparc.local:10000" \
    #   minio/mc admin prometheus generate local
 - job_name: minio-job
   bearer_token: ${MINIO_PROMETHEUS_TOKEN}
   metrics_path: /minio/prometheus/metrics
   scheme: https
   static_configs:
   - targets: ['${STORAGE_DOMAIN}']

scrape_configs:
  # SIMCORE -------------------------------------------------------------------
  - job_name: "simcore"
    relabel_configs:
      - source_labels: [__meta_dns_name]
        regex: ^(.*?)[_-].*$
        replacement: $1
        target_label: deployment
      - source_labels: [__meta_dns_name]
        regex: ^.*?[_-](.*)$
        replacement: $1
        target_label: service_name
    dns_sd_configs:
      - names:
          - "production_webserver"
          - "staging_webserver"
        type: "A"
        port: 8080
      - names:
          - "production_storage"
          - "staging_storage"
        type: "A"
        port: 8080
      - names:
          - "production_director"
          - "staging_director"
        type: "A"
        port: 8080
      - names:
          - "production_rabbit"
          - "staging_rabbit"
        type: "A"
        port: 15692
      - names:
          - "production_traefik"
          - "staging_traefik"
        type: "A"
        port: 8082
      - names:
          - "staging-redis-exporter"
          - "production-redis-exporter"
        type: "A"
        port: 9121
      - names:
          - "staging-postgres-exporter"
          - "production-postgres-exporter"
        type: "A"
        port: 9187