{
 "title": "MinIO overview",
 "description": "MinIO dashboard - https://min.io/",
 "tags": [
  "minio",
  "object-storage",
  "prometheus"
 ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "instance",
    "query": "label_values(minio_version_info,instance)"
   },
   {
    "name": "interval",
    "query": "1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   }
  ]
 },
 "panels": [
  {
   "title": "Uptime",
   "type": "singlestat",
   "description": "Start time of the MinIO server",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 0 },
   "format": "dtdurations",
   "valueName": "avg",
   "targets": [
    {
     "expr": "time() - max(process_start_time_seconds)",
     "legendFormat": "Start time of the MinIO servers"
    }
   ]
  },
  {
   "title": "Total disks",
   "type": "singlestat",
   "description": "Total number of disks for current MinIO server instances",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 0 },
   "format": "short",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(minio_disks_total)",
     "legendFormat": "Total number of disks for current MinIO server instances"
    }
   ]
  },
  {
   "title": "Offline disks",
   "type": "singlestat",
   "description": "Total number of offline disks for current MinIO server instances",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 0 },
   "format": "short",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(minio_disks_offline)",
     "legendFormat": "Total number of offline disks for current MinIO server instances"
    }
   ]
  },
  {
   "title": "Disk total size (Max)",
   "type": "singlestat",
   "description": "Total size of the disk for current MinIO server instances",
   "gridPos": { "h": 3, "w": 4, "x": 12, "y": 0 },
   "format": "decbytes",
   "valueName": "max",
   "targets": [
    {
     "expr": "sum(disk_storage_total)",
     "legendFormat": "Total size of the disk for current MinIO server instances"
    }
   ]
  },
  {
   "title": "Disk total used (Max)",
   "type": "singlestat",
   "description": "Total disk space used for current MinIO server instances",
   "gridPos": { "h": 3, "w": 4, "x": 16, "y": 0 },
   "format": "decbytes",
   "valueName": "max",
   "targets": [
    {
     "expr": "sum(disk_storage_used)",
     "legendFormat": "Total disk space used for current MinIO server instances"
    }
   ]
  },
  {
   "title": "Disk total available (Max)",
   "type": "singlestat",
   "description": "Total available disk space for current MinIO server instances",
   "gridPos": { "h": 3, "w": 4, "x": 20, "y": 0 },
   "format": "decbytes",
   "valueName": "max",
   "targets": [
    {
     "expr": "sum(disk_storage_available)",
     "legendFormat": "Total available disk space for current MinIO server instances"
    }
   ]
  },
  {
   "title": "Disks",
   "type": "graph",
   "description": "Number of total/offline disks for current MinIO server instances",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 3 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "minio_disks_offline{instance=~\"$instance\"}",
     "legendFormat": "Offline {{instance}}"
    },
    {
     "expr": "minio_disks_total{instance=~\"$instance\"}",
     "legendFormat": "Total {{instance}}"
    }
   ]
  },
  {
   "title": "Disk Usage",
   "type": "graph",
   "description": "Total disk space used for current MinIO server instances",
   "gridPos": { "h": 6, "w": 8, "x": 8, "y": 3 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "sum(disk_storage_used{instance=~\"$instance\"}) by (instance)",
     "legendFormat": "used {{instance}}"
    },
    {
     "expr": "sum(disk_storage_total{instance=~\"$instance\"}) by (instance)",
     "legendFormat": "total {{instance}}"
    }
   ]
  },
  {
   "title": "Disk Percentage Utilization",
   "type": "graph",
   "description": "Percentage disk space used for current MinIO server instances",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 3 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "sum(disk_storage_used{instance=~\"$instance\"}) by (instance) / sum(disk_storage_total{instance=~\"$instance\"}) by (instance) * 100",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Memory Stats",
   "type": "graph",
   "description": "MinIO server instances memory usages",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "process_resident_memory_bytes{instance=~\"$instance\"}",
     "legendFormat": "resident {{instance}}"
    },
    {
     "expr": "process_virtual_memory_bytes{instance=~\"$instance\"}",
     "legendFormat": "virtual {{instance}}"
    }
   ]
  },
  {
   "title": "CPU Stats",
   "type": "graph",
   "description": "Total user and system CPU time spent in percentage by MinIO server instances",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "rate(process_cpu_seconds_total{instance=~\"$instance\"}[$interval])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Data Transmitted",
   "type": "graph",
   "description": "Data sent/received by current MinIO server instances",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "rate(s3_tx_bytes_total{instance=~\"$instance\"}[$interval])",
     "legendFormat": "Sent {{instance}}"
    },
    {
     "expr": "rate(s3_rx_bytes_total{instance=~\"$instance\"}[$interval])",
     "legendFormat": "Received {{instance}}"
    }
   ]
  },
  {
   "title": "Internode Data Transmitted",
   "type": "graph",
   "description": "Internode data sent/received by current MinIO server instances",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 17 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "rate(internode_tx_bytes_total{instance=~\"$instance\"}[$interval])",
     "legendFormat": "Sent {{instance}}"
    },
    {
     "expr": "rate(internode_rx_bytes_total{instance=~\"$instance\"}[$interval])",
     "legendFormat": "Received {{instance}}"
    }
   ]
  },
  {
   "title": "S3 Total Requests",
   "type": "graph",
   "description": "Total number of S3 requests in current MinIO server instances",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(s3_requests_total{instance=~\"$instance\"}) by (api)",
     "legendFormat": "{{api}}"
    }
   ]
  },
  {
   "title": "S3 Active Requests",
   "type": "graph",
   "description": "Total number of active S3 requests in current MinIO server instances",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 24 },
   "yaxes": [
    { "format": "opm" }
   ],
   "targets": [
    {
     "expr": "rate(s3_requests_current{instance=~\"$instance\"}[$interval])  ",
     "legendFormat": "{{instance}} {{api}}"
    }
   ]
  },
  {
   "title": "S3 Errors Requests",
   "type": "graph",
   "description": "Total number of errors in s3 requests in current MinIO server instances",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 24 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(s3_errors_total{instance=~\"$instance\"}) by (api)",
     "legendFormat": "{{api}}"
    }
   ]
  },
  {
   "title": "S3 Requests Latency",
   "type": "graph",
   "description": "Latency information of the requests on MinIO server instances",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 31 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "s3_ttfb_seconds_sum{instance=~\"$instance\"}",
     "legendFormat": "{{instance}} {{api}}"
    }
   ]
  },
  {
   "title": "HTTP Request Status",
   "type": "graph",
   "description": "HTTP request status of MinIO server response",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 31 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(promhttp_metric_handler_requests_total{instance=~\"$instance\"}) by (code)",
     "legendFormat": "{{code}}"
    }
   ]
  }
 ]
}