version: '3.7'
services:
  prometheus:
    dns: 
      8.8.8.8
    deploy:
      placement:
        constraints:
        - node.labels.traefik==true
  grafana:
    dns: 
      8.8.8.8
  postgres-exporter:
    dns:
      8.8.8.8
    image: bitnami/postgres-exporter:0.8.0
    networks:
      - internal
      - monitored
    environment:
      - DATA_SOURCE_NAME=${POSTGRES_EXPORTER_DATA_SOURCE_NAME}
    deploy:
      resources:
        limits:
          memory: 128M
        reservations:
          memory: 64M
  redis-exporter:
    image: oliver006/redis_exporter
    networks:
      - internal
      - monitored
    environment:
      - REDIS_ADDR=${REDIS_EXPORTER_DATA_SOURCE_NAME}
      - REDIS_EXPORTER_CHECK_KEYS=user_id*client_session_id*alive, user_id*client_session_id*resources
    deploy:
      resources:
        limits:
          memory: 128M
        reservations:
          memory: 64M
