version: '3.7'
services:
  staging-postgres-exporter:
    image: bitnami/postgres-exporter:0.8.0
    networks:
      - internal
      - monitored
    environment:
      - DATA_SOURCE_NAME=${STAGING_POSTGRES_EXPORTER_DATA_SOURCE_NAME}
    deploy:
      resources:
        limits:
          memory: 128M
        reservations:
          memory: 64M
  production-postgres-exporter:
    image: bitnami/postgres-exporter:0.8.0
    networks:
      - internal
      - monitored
    environment:
      - DATA_SOURCE_NAME=${PRODUCTION_POSTGRES_EXPORTER_DATA_SOURCE_NAME}
    deploy:
      resources:
        limits:
          memory: 128M
        reservations:
          memory: 64M

  staging-redis-exporter:
    image: oliver006/redis_exporter
    networks:
      - internal
      - monitored
    environment:
      - REDIS_ADDR=${STAGING_REDIS_EXPORTER_DATA_SOURCE_NAME}
      - REDIS_EXPORTER_CHECK_KEYS=user_id*client_session_id*alive, user_id*client_session_id*resources
    deploy:
      resources:
        limits:
          memory: 128M
        reservations:
          memory: 64M
  production-redis-exporter:
    image: oliver006/redis_exporter
    networks:
      - internal
      - monitored
    environment:
      - REDIS_ADDR=${PRODUCTION_REDIS_EXPORTER_DATA_SOURCE_NAME}
      - REDIS_EXPORTER_CHECK_KEYS=user_id*client_session_id*alive, user_id*client_session_id*resources
    deploy:
      resources:
        limits:
          memory: 128M
        reservations:
          memory: 64M

  gitlab-ci-pipelines-exporter:
    image: mvisonneau/gitlab-ci-pipelines-exporter:v0.4.4
    # https://github.com/mvisonneau/gitlab-ci-pipelines-exporter
    environment:
      GCPE_CONFIG: /etc/gitlab-ci-pipelines-exporter/config.yml
      GCPE_LOG_LEVEL: info
    networks:
      - internal
      - monitored
    volumes:
      - type: bind
        source: ./gitlab-ci-pipelines-exporter
        target: /etc/gitlab-ci-pipelines-exporter
    deploy:
      labels:
        - prometheus-job=gitlab-ci-pipelines-exporter
        - prometheus-port=8080
      placement:
        constraints:
          - node.role==manager
      resources:
        limits:
          memory: 128M
        reservations:
          memory: 64M